WPM_ENABLE = yes
OLED_DRIVER_ENABLE = yes
ENCODER_ENABLE = no
NKRO_ENABLE = yes
SPLIT_KEYBOARD = yes
SPLIT_LAYER_STATE_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes

BOOTLOADER = rp2040